package x_terminating.error;

/**
 * Single responsibility:
 * //todo
 */
final class RethrownException extends RuntimeException {
}
